# Generated by Django 3.2.7 on 2021-10-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edinet_code', models.CharField(max_length=128, verbose_name='EDINETコード')),
                ('name', models.CharField(max_length=128, verbose_name='会社名')),
                ('end_date', models.DateField(blank=True, verbose_name='期末日')),
                ('filling_date', models.DateField(blank=True, verbose_name='提出日')),
                ('fiscal_year', models.CharField(max_length=128, verbose_name='事業年度')),
                ('audit_fee', models.IntegerField(blank=True, verbose_name='監査報酬')),
                ('audit_fee_networkfirm', models.IntegerField(blank=True, null=True, verbose_name='監査報酬(ネットワークファーム)')),
                ('auditor', models.CharField(max_length=128, verbose_name='監査法人')),
                ('kam_title_1', models.CharField(blank=True, max_length=128, null=True, verbose_name='KAM1')),
                ('kam_title_2', models.CharField(blank=True, max_length=128, null=True, verbose_name='KAM2')),
                ('kam_title_3', models.CharField(blank=True, max_length=128, null=True, verbose_name='KAM3')),
                ('kam_title_4', models.CharField(blank=True, max_length=128, null=True, verbose_name='KAM4')),
                ('kam_title_5', models.CharField(blank=True, max_length=128, null=True, verbose_name='KAM5')),
                ('kam_description_1', models.TextField(blank=True, null=True, verbose_name='KAM1の内容及び決定理由')),
                ('kam_description_2', models.TextField(blank=True, null=True, verbose_name='KAM2の内容及び決定理由')),
                ('kam_description_3', models.TextField(blank=True, null=True, verbose_name='KAM3の内容及び決定理由')),
                ('kam_description_4', models.TextField(blank=True, null=True, verbose_name='KAM4の内容及び決定理由')),
                ('kam_description_5', models.TextField(blank=True, null=True, verbose_name='KAM5の内容及び決定理由')),
                ('kam_audit_description_1', models.TextField(blank=True, null=True, verbose_name='KAM1の監査上の対応')),
                ('kam_audit_description_2', models.TextField(blank=True, null=True, verbose_name='KAM2の監査上の対応')),
                ('kam_audit_description_3', models.TextField(blank=True, null=True, verbose_name='KAM3の監査上の対応')),
                ('kam_audit_description_4', models.TextField(blank=True, null=True, verbose_name='KAM4の監査上の対応')),
                ('kam_audit_description_5', models.TextField(blank=True, null=True, verbose_name='KAM5の監査上の対応')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
